module.exports = [
    / Alternative rock/i,
    / Britpop/i,
    / Post-Britpop/i,
    / Dream pop/i,
    / Grunge/i,
    / Post-grunge/i,
    / Indie rock/i,
    / Indie pop/i,
    / Dunedin Sound/i,
    / Twee Pop/i,
    / Post-punk revival/i,
    / Industrial rock/i,
    / Noise pop/i,
    / Nu metal/i,
    / Post-rock/i,
    / Post-metal/i,
    / Sadcore/i,
    / Shoegaze/i,
    / Slowcore/i,
    / Art rock/i,
    / Beat music/i,
    / Chinese rock/i,
    / Christian rock/i,
    / Electronicore/i,
    / Dark cabaret/i,
    / Experimental rock/i,
    / Electronic rock/i,
    / Folk rock/i,
    / Garage rock/i,
    / Glam rock/i,
    / Hard rock/i,
    / Heavy metal/i,
    / Alternative metal/i,
    / Nu metal/i,
    / Black metal/i,
    / Viking metal/i,
    / Christian metal/i,
    / Death metal/i,
    / Melodic death metal/i,
    / Technical death metal/i,
    / Goregrind/i,
    / Doom metal/i,
    / Epic doom/i,
    / Funeral doom/i,
    / Traditional doom/i,
    / Drone metal/i,
    / Folk metal/i,
    / Celtic metal/i,
    / Medieval metal/i,
    / Funk metal/i,
    / Glam metal/i,
    / Gothic metal/i,
    / Industrial metal/i,
    / Metalcore/i,
    / Deathcore/i,
    / Mathcore/i,
    / Power metal/i,
    / Progressive metal/i,
    / Djent/i,
    / Rap metal/i,
    / Sludge metal/i,
    / Speed metal/i,
    / Stoner rock/i,
    / Symphonic metal/i,
    / Thrash metal/i,
    / Crossover thrash/i,
    / Groove metal/i,
    / Jazz rock/i,
    / Math rock/i,
    / New wave/i,
    / World fusion/i,
    / Paisley Underground/i,
    / Desert rock/i,
    / Pop rock/i,
    / Power pop/i,
    / Soft rock/i,
    / Progressive rock/i,
    / Canterbury scene/i,
    / Krautrock/i,
    / New prog/i,
    / Rock in Opposition/i,
    / Space rock/i,
    / Psychedelic rock/i,
    / Acid rock/i,
    / Freakbeat/i,
    / Neo-psychedelia/i,
    / Raga rock/i,
    / Punk rock/i,
    / Anarcho punk/i,
    / Crust punk/i,
    / D-beat/i,
    / Art punk/i,
    / Christian punk/i,
    / Deathrock/i,
    / Digital hardcore/i,
    / Folk punk/i,
    / Celtic punk/i,
    / Cowpunk/i,
    / Garage punk/i,
    / Grindcore/i,
    / Crustgrind/i,
    / Noisegrind/i,
    / Hardcore punk/i,
    / Post-hardcore/i,
    / Screamo/i,
    / Thrashcore/i,
    / Crossover thrash/i,
    / Powerviolence/i,
    / Street punk/i,
    / Horror punk/i,
    / Pop punk/i,
    / Psychobilly/i,
    / Riot grrrl/i,
    / Ska punk/i,
    / Skate punk/i,
    / Post-punk/i,
    / Gothic rock/i,
    / No wave/i,
    / Noise rock/i,
    / Rap rock/i,
    / Rapcore/i,
    / Rock and roll/i,
    / Southern rock/i,
    / Sufi rock/i,
    / Surf rock/i,
    / Worldbeat/i,
    / Acid jazz/i,
    / Avant-garde jazz/i,
    / Bebop/i,
    / Boogie-woogie/i,
    / Bossa nova/i,
    / British dance/i,
    / Cape jazz/i,
    / Chamber jazz/i,
    / Continental Jazz/i,
    / Cool jazz/i,
    / Crossover jazz/i,
    / Dixieland/i,
    / European free jazz/i,
    / Hard bop/i,
    / Jazz blues/i,
    / Jazz-funk/i,
    / Jazz fusion/i,
    / Jazz rap/i,
    / Jazz rock/i,
    / Latin jazz/i,
    / Livetronica/i,
    / Mainstream jazz/i,
    / Modal jazz/i,
    / Neo-bop jazz/i,
    / Neo-swing/i,
    / Novelty ragtime/i,
    / Nu jazz/i,
    / Orchestral jazz/i,
    / Post-bop/i,
    / Punk jazz/i,
    / Ragtime/i,
    / Shibuya-kei/i,
    / Ska jazz/i,
    / Smooth jazz/i,
    / Soul jazz/i,
    / Stride jazz/i,
    / Straight-ahead jazz/i,
    / Swing/i,
    / Third stream/i,
    / Trad jazz/i,
    / Vocal jazz/i,
    / West Coast jazz/i,
    / Ambient/i,
    / Ambient dub/i,
    / Ambient house/i,
    / Ambient techno/i,
    / Dark ambient/i,
    / Drone/i,
    / Illbient/i,
    / Lowercase/i,
    / Asian Underground/i,
    / Breakbeat/i,
    / Acid breaks/i,
    / Baltimore Club/i,
    / Big beat/i,
    / Breakbeat hardcore/i,
    / Broken beat/i,
    / Florida breaks/i,
    / Nu skool breaks/i,
    / 4-beat/i,
    / Chiptune/i,
    / Bitpop/i,
    / Nintendocore/i,
    / Yorkshire Bleeps and Bass/i,
    / Disco/i,
    / Cosmic disco/i,
    / Disco polo/i,
    / Europop/i,
    / Euro disco/i,
    / Space disco/i,
    / Italo disco/i,
    / Nu-disco/i,
    / Downtempo/i,
    / Acid jazz/i,
    / Balearic Beat/i,
    / Chill out/i,
    / Dub/i,
    / Dubtronica/i,
    / Ethnic electronica/i,
    / Moombahton/i,
    / New-age/i,
    / Nu jazz/i,
    / Trip hop/i,
    / Drum and bass/i,
    / Darkcore/i,
    / Darkstep/i,
    / Drumfunk/i,
    / Drumstep/i,
    / Hardstep/i,
    / Intelligent drum and bass/i,
    / Jump-Up/i,
    / Liquid funk/i,
    / Neurofunk/i,
    / Oldschool jungle/i,
    / Darkside jungle/i,
    / Ragga-jungle/i,
    / Raggacore/i,
    / Sambass/i,
    / Techstep/i,
    / Crunk/i,
    / Electro backbeat/i,
    / Electro-grime/i,
    / Electroacoustic/i,
    / Electronica/i,
    / Chillwave/i,
    / Electronic art music/i,
    / EDM/i,
    / Folktronica/i,
    / Freestyle/i,
    / IDM/i,
    / Glitch/i,
    / Laptronica/i,
    / Skweee/i,
    / Sound art/i,
    / Synthcore/i,
    / Electronic rock/i,
    / Alternative dance/i,
    / Baggy/i,
    / Madchester/i,
    / Dance-punk/i,
    / Dance-rock/i,
    / Dark Wave/i,
    / Electroclash/i,
    / Electronicore/i,
    / Electropunk/i,
    / Ethereal wave/i,
    / Indietronica/i,
    / New rave/i,
    / Space rock/i,
    / Synthpop/i,
    / Synthpunk/i,
    / Eurodance/i,
    / Bubblegum dance/i,
    / Italo dance/i,
    / Turbofolk/i,
    / Hardcore/i,
    / Hard dance/i,
    / Bouncy house/i,
    / Bouncy techno/i,
    / Breakcore/i,
    / Darkcore/i,
    / Digital hardcore/i,
    / Doomcore/i,
    / Dubstyle/i,
    / Gabber/i,
    / Happy hardcore/i,
    / Hardstyle/i,
    / Jumpstyle/i,
    / Makina/i,
    / Speedcore/i,
    / Terrorcore/i,
    / Hi-NRG/i,
    / Eurobeat/i,
    / Hard NRG/i,
    / New Beat/i,
    / House/i,
    / Acid house/i,
    / Chicago house/i,
    / Deep house/i,
    / Diva house/i,
    / Dutch house/i,
    / Electro house/i,
    / French house/i,
    / Freestyle house/i,
    / Funky house/i,
    / Ghetto house/i,
    / Hardbag/i,
    / Hip house/i,
    / Italo house/i,
    / Latin house/i,
    / Minimal house/,
    / Microhouse/i,
    / Progressive house/i,
    / Swing house/i,
    / Tech house/i,
    / Tribal house/i,
    / Vocal house/i,
    / Industrial/i,
    / Aggrotech/i,
    / Coldwave/i,
    / Cybergrind/i,
    / Dark electro/i,
    / Death industrial/i,
    / Futurepop/i,
    / Electro-industrial/i,
    / Industrial metal/i,
    / Industrial rock/i,
    / Noise/i,
    / Japanoise/i,
    / Power noise/i,
    / Power electronics/i,
    / Witch House/,
    / Drag/i,
    / Post-disco/i,
    / Boogie/i,
    / Dance-pop/i,
    / Electropop/i,
    / Progressive/i,
    / Progressive breaks/i,
    / Progressive drum & bass/i,
    / Progressive House/i,
    / Disco house/i,
    / Dream house/i,
    / Space house/i,
    / Progressive techno/i,
    / Techno/i,
    / Acid techno/i,
    / Detroit techno/i,
    / Free tekno/i,
    / Ghettotech/i,
    / Minimal/i,
    / Nortec/i,
    / Tecno brega/i,
    / Techno-DNB/i,
    / Technopop/i,
    / Toytown Techno/i,
    / Trance/i,
    / Acid trance/i,
    / Classic trance/i,
    / Dream trance/i,
    / Psychedelic trance/i,
    / Dark psytrance/i,
    / Full on/i,
    / Psyprog/i,
    / Psybreaks/i,
    / Suomisaundi/i,
    / Hard trance/i,
    / Tech trance/i,
    / Uplifting trance/i,
    / Orchestral Uplifting/i,
    / Vocal trance/i,
    / 2-step/i,
    / Bassline/i,
    / Breakstep/i,
    / Dubstep/i,
    / Trap/i,
    / Funky/i,
    / Grime/i,
    / Speed garage/i,
    / Folk/i,
    / Contemporary folk/i,
    / Celtic/i,
    / Indie folk/i,
    / Neofolk/i,
    / Progressive folk/i,
    / Anti-folk/i,
    / Freak folk/i,
    / Filk/i,
    / Industrial folk/i,
    / Techno-folk/i,
    / Psychedelic folk/i,
    / Sung poetry/i,
    / Western/i,
    / Rock/i,
    / Rap/i,
    / Hip-hop/i,
    / Punk/i
];